run:
  timeout: 10m
  modules-download-mode: vendor

issues:
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019: codec.BasicHandle is deprecated"
  - linters:
      - staticcheck
    text: "SA1019: \"github.com/Azure/azure-sdk-for-go"
  # This is set to false to disregard the default EXC0011 exclusion
  # which shadows all the ST* checks. Refer https://github.com/golangci/golangci-lint/issues/2281
  exclude-use-default: false
  exclude-dirs-use-default: true

linters-settings:
  stylecheck:
    # added additional checks for comments in Go.
    # Refer https://staticcheck.io/docs/options#checks for details
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - github.com/onsi/ginkgo
      - github.com/onsi/gomega

linters:
  disable-all: true
  enable:
    - gofmt
    - unused
    - gosimple
    - govet
    - staticcheck
    - whitespace
    - stylecheck
